# Generated by Django 4.0.3 on 2022-04-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(verbose_name=5)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
