# Generated by Django 4.0.3 on 2022-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='direccion',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='tittle',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
