# Generated by Django 4.0.3 on 2022-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
    ]
