# Generated by Django 4.0.3 on 2022-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
