# Generated by Django 4.0.3 on 2022-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_estacionamiento_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
