# Generated by Django 4.0.3 on 2022-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_estacionamiento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='promedio',
            field=models.IntegerField(default=0),
        ),
    ]
