# Generated by Django 4.0.3 on 2022-06-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=500)),
                ('nMeses', models.IntegerField()),
                ('nCuenta', models.CharField(max_length=20)),
                ('fechaInicio', models.DateField()),
                ('nEstacionamiento', models.IntegerField(blank=True, null=True)),
                ('nInscripcion', models.IntegerField(blank=True, null=True)),
                ('anoInscripcion', models.DateField(blank=True, null=True)),
                ('nombreEsta', models.CharField(blank=True, max_length=500, null=True)),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estacionamiento')),
            ],
        ),
    ]
