# Generated by Django 4.0.3 on 2022-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosContrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontrato',
            name='apellidoArrendador',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datoscontrato',
            name='direccionArrendador',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='datoscontrato',
            name='nombreArrendador',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datoscontrato',
            name='rutArrendador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
