# Generated by Django 4.0.3 on 2022-06-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosContrato', '0002_alter_datoscontrato_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscontrato',
            old_name='user',
            new_name='estacionamiento',
        ),
    ]
