# Generated by Django 4.0.3 on 2022-06-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosContrato', '0004_datoscontrato_nestacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontrato',
            name='anoInscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datoscontrato',
            name='nInscripcion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
