# Generated by Django 4.0.3 on 2022-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosContrato', '0005_datoscontrato_anoinscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontrato',
            name='nombreEsta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
