# Generated by Django 4.0.3 on 2022-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=500)),
                ('apellido_P', models.CharField(max_length=50)),
                ('apellido_M', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('admin', models.BooleanField(default=False)),
                ('celular', models.CharField(max_length=9)),
                ('imagen', models.ImageField(upload_to='perfil')),
            ],
        ),
    ]
