# Generated by Django 4.0.3 on 2022-06-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=5000)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estacionamiento')),
            ],
        ),
    ]
