# Generated by Django 4.0.3 on 2022-06-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
