# Generated by Django 4.0.3 on 2022-04-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parking_id',
            new_name='parking',
        ),
    ]
